# Generated by Django 4.1.2 on 2023-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="is_package_active",
            field=models.BooleanField(default=False),
        ),
    ]
