# Generated by Django 4.1.2 on 2023-01-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="education",
        ),
        migrations.RemoveField(
            model_name="freelancer",
            name="skills",
        ),
        migrations.AddField(
            model_name="education",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="skills",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.freelancer"
            ),
        ),
    ]
