# Generated by Django 4.1.2 on 2023-01-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_freelancer_education_remove_freelancer_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="experience",
        ),
        migrations.AddField(
            model_name="experience",
            name="experience",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.freelancer",
            ),
        ),
        migrations.AddField(
            model_name="skills",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="education",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="skills",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
