# Generated by Django 4.1.2 on 2022-12-24 11:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_createpost_education_experience_freelancerbio_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_to
            ),
        ),
    ]
