# Generated by Django 4.1.2 on 2023-01-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_freelancer_is_package_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="post_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
