# Generated by Django 4.1.2 on 2023-01-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_freelancer_experience_experience_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skills",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
