# Generated by Django 4.1.2 on 2023-01-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_skills_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skills",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
