# Generated by Django 4.1.2 on 2022-12-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_client_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FreelancerBio",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="location",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="name",
        ),
        migrations.AddField(
            model_name="client",
            name="bio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="education",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="languages",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="education",
            name="university",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="experience",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="place",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="bio",
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="education",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.education",
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="experience",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.experience",
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="skills",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.skills"
            ),
        ),
        migrations.AddField(
            model_name="skills",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skills",
            name="skills",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="skills",
            name="title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="is_currently_working",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
