# Generated by Django 4.1.2 on 2023-01-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_experience_no_of_years"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="education",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="experience",
            new_name="user",
        ),
    ]
