# Generated by Django 4.1.2 on 2022-12-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_freelancer_title_alter_freelancer_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="social_media_links",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
