# Generated by Django 4.1.2 on 2023-01-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_experience_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="languages",
        ),
    ]
