# Generated by Django 4.1.2 on 2022-12-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_freelancer_social_media_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="skills",
        ),
    ]
