# Generated by Django 4.1.2 on 2023-01-07 12:27

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_education_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="createpost",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="createpost",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="createpost",
            name="price",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="createpost",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="createpost",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
