# Generated by Django 4.1.2 on 2023-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_category_createpost_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createpost",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
