# Generated by Django 4.1.2 on 2023-01-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_createpost_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpost",
            name="price",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
