# Generated by Django 4.1.2 on 2023-01-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_category_category_category_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.AddField(
            model_name="createpost",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="createpost",
            name="sub_category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subcategory",
            ),
        ),
    ]
