# Generated by Django 4.1.2 on 2023-01-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_createpost_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createpost",
            name="category",
        ),
    ]
