# Generated by Django 4.1.2 on 2023-01-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_createpost_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
