# Generated by Django 4.1.2 on 2023-01-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_createpost_sub_category_alter_createpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpost",
            name="description",
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
