# Generated by Django 4.1.2 on 2023-01-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_createpost_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpost",
            name="keyfeatures",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
