# Generated by Django 4.1.2 on 2023-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_createpost_keyfeatures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
