# Generated by Django 4.1.2 on 2023-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_freelancer_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "no_of_posts",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
