# Generated by Django 4.1.2 on 2023-01-14 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("first_name", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("username", models.CharField(blank=True, max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "expiration_time",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("new_password", models.CharField(blank=True, max_length=20)),
                ("confirm_new_password", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("otp", models.CharField(blank=True, max_length=40, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_freelancer", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
