# Generated by Django 4.1.4 on 2022-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
