# Generated by Django 4.1.2 on 2022-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_user_is_freelancer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirm_new_password",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="new_password",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
