# Generated by Django 4.1.2 on 2022-12-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0004_user_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="img",
        ),
    ]
