# Generated by Django 4.1.2 on 2022-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_remove_user_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
