# Generated by Django 4.1.2 on 2023-01-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0006_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
