# Generated by Django 4.1.2 on 2023-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0007_user_is_verified_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
