# Generated by Django 4.1.2 on 2023-01-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0008_alter_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_interval",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
