# Generated by Django 4.1.2 on 2023-01-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0009_user_otp_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp_interval",
        ),
        migrations.AddField(
            model_name="user",
            name="expiration_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
