# Generated by Django 4.1.2 on 2023-01-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0010_remove_user_otp_interval_user_expiration_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_user",
        ),
    ]
