# Generated by Django 4.1.2 on 2023-01-14 09:03

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=payment.models.upload_to
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=800, null=True),
                ),
                (
                    "keyfeatures",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "Freelancer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.freelancer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "no_of_posts",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RazorpayPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
                (
                    "Freelancer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.freelancer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Freelancer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.freelancer",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.packages",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.razorpaypayment",
                    ),
                ),
                (
                    "posts",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.createpost",
                    ),
                ),
            ],
        ),
    ]
