# Generated by Django 4.1.2 on 2023-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerpost",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
