# Generated by Django 4.1.2 on 2023-01-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_freelancerpost_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancerpost",
            name="posts",
        ),
    ]
